num_i_a: 5
num_ii: 5
chunk_size: 1000
time_steps: 1152
label_dims: 7
output_prefix: "optimized_linear"
i_a_coeff_path: "/media/data16/siebe/datasets/coefficients_i_a.csv"
ii_coeff_path: "/media/data16/siebe/datasets/coefficients_ii.csv"
i_a_sampled_coeff_path: null
ii_sampled_coeff_path: null
seed: 0 
save_vel: false
sampling_rate: 240
optimal_lengths: [
    311.7433,
    98.2861,
    49.1894,
    111.1101,
    102.2885,
    77.8912,
    394.6737,
    153.2794,
    188.8929,
    128.3927,
    116.8948,
    76.9059,
    89.5907,
    133.1054,
    137.4615,
    25.9443,
    127.1979,
    177.4619,
    57.6238,
    101.9763,
    92.9367,
    76.5367,
    63.6004,
    179.1151,
    51.3648,
]  # List of 25 values, from optimal_lengths.npy (myo bimanual model, generate_spindle_coefficients.py)
muscles: [
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24
] 
